apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  # 'name' must match the filename of the manifest. The name defines how
  # the plugin is invoked, for example: `kubectl restart`
  name: cpbase64
spec:
  # 'version' is a valid semantic version string (see semver.org). Note the prefix 'v' is required.
  version: "v0.1.7"
  # 'homepage' usually links to the GitHub repository of the plugin
  homepage: https://github.com/freeella/kubectl-cpbase64
  # 'shortDescription' explains what the plugin does in only a few words
  shortDescription: "Alternative to 'cp' using base64 instead of tar"
  description: |
    Not busybox based Docker images often do not ship 'tar' by default.
    This command 'kubectl cpbase64' uses 'base64' instead.
    The goal is to be in sync with command line syntax of 'kubectl cp'.
  # 'platforms' specify installation methods for various platforms (os/arch)
  # See all supported platforms below.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    # 'uri' specifies .zip or .tar.gz archive URL of a plugin
    uri: https://github.com/freeella/kubectl-cpbase64/releases/download/v0.1.7/kubectl-cpbase64.release-v0.1.7.zip
    # 'sha256' is the sha256sum of the url (archive file) above
    sha256: 924b96ff5b642e859c942beeb6f9d4bbb2a03a11ca1b806ffee7ba6159719b43
    # 'files' lists which files should be extracted out from downloaded archive
    files:
    - from: "kubectl-cpbase64"
      to: "cpbase64.bash"
    - from: "LICENSE"
      to: "."
    # 'bin' specifies the path to the the plugin executable among extracted files
    bin: cpbase64.bash