on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

name: Unit Tests

jobs:
  test:
    permissions:
        contents: read
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Setup dependencies
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          # See available:
          # - k3s release channels at https://github.com/k3s-io/k3s/blob/HEAD/channel.yaml
          # - k3s versions at https://github.com/k3s-io/k3s/tags
          # - helm versions at https://github.com/helm/helm/tags
          k3s-channel: latest
          # k3s-version: v1.29.0+k3s1
          # helm-version: v3.13.0

      - name: Verify function of k8s, kubectl, and helm
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl version
          kubectl get pods --all-namespaces

      - name: Setup Test PODs
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cpbase64
            labels:
              name: cpbase64
          ---
          apiVersion: v1
          kind: Pod
          metadata:
            name: cpbase64-pod
            namespace: cpbase64
            labels:
              name: cpbase64-pod
          spec:
            containers:
              - name: cpb64
                image: busybox:latest
                command: ["/bin/tail"]
                args: ["-f","/dev/null"]
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: cpbase64-deployment
            namespace: cpbase64
            labels:
              app: cpbase64-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: cpbase64-deployment
            template:
              metadata:
                labels:
                  app: cpbase64-deployment
              spec:
                containers:
                  - name: cpb64
                    image: busybox:latest
                    command: ["/bin/tail"]
                    args: ["-f","/dev/null"]
          EOF

          kubectl get namespaces
          kubectl get pods -A
          kubectl get deployments -n cpbase64
          kubectl get pods -n cpbaseb64

          kubectl wait --for=condition=ready pod --namespace cpbase64 -l name=cpbase64-pod
          kubectl wait --for=condition=ready pod --namespace cpbase64 -l app=cpbase64-deployment

          kubectl get pods -n cpbaseb64

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0

      # source code starts here 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Version
        id: vars
        run: |
          PROJECT_VERSION=${{ github.ref }}
          PROJECT_VERSION=$( echo $PROJECT_VERSION | sed 's|refs/tags/||g' )
          # allow manual run
          if [[ "${{ github.event_name }}"  == 'workflow_dispatch' ]]
          then
            PROJECT_VERSION=v0.0.1-test
          fi
          echo "event=${{ github.event_name }}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >>"$GITHUB_ENV"
          sed -i "s|^CPB64_VERSION=.*|CPB64_VERSION=$PROJECT_VERSION|g" src/main/kubectl-cpbase64

      - name: Run Syntax Unit Tests
        run: |
          set -x
          # kubectl seems always pre-installed; not needed for syntax checks if not installed
          command -v kubectl 2>/dev/null || alias kubectl=true
          which bats
          which kubectl
          bats -r src/tests/
