on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:


name: Create Release

jobs:
  release:
    permissions:
        contents: write
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set version
        id: vars
        run: |
          export project_version=${{ github.ref }}
          # allow manual run
          if [[ "${{ github.event_name }}  == 'workflow_dispatch' ]]
          then
            export project_version=v0.0.1
          fi
          echo "event=${{ github.event_name}}"
          echo "project_version=${{ env.project_version }}"
          echo "project_version=${project_version}" >>$GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.vars.outputs.project_version }}
          release_name: Release ${{ steps.vars.outputs.project_version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
