on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Use version field:'
        type: boolean
      version:
        description: 'Version name be released: v0.0.0'
        type: string

name: Release to Krew

jobs:
  release:
    permissions:
        contents: read
    name: Release to Krew
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: vars
        run: |
          # - if a tag was selected
          if [[ '${{ github.ref }}'  =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            PROJECT_VERSION=${{ github.ref }}
            PROJECT_VERSION=$( echo $PROJECT_VERSION | sed 's|refs/tags/||g' )
          # - or the version number was given via text field
          elif [ '${{inputs.confirm}}' == 'true' ]
          then
            if [[ '${{inputs.version}}' =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
            then
              PROJECT_VERSION='${{inputs.version}}'
            else
              echo "ERROR: Invalid version '${{inputs.version}}' given! Must have format 'v0.0.0'!" >&2
              false
            fi
          # - not a valid version
          else
            echo "ERROR: No tag selected or manual input not confirmed!" >&2
            false
          fi
          echo "PROJECT_VERSION=${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >>"$GITHUB_ENV"
          PROJECT_VERSION_REF="refs/tags/${PROJECT_VERSION}"
          echo "PROJECT_VERSION_REF=${PROJECT_VERSION}"
          echo "PROJECT_VERSION_REF=${PROJECT_VERSION}" >>"$GITHUB_ENV"
          

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: main

      - name: Print new version in krew-index
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          github.ref: ${{ env.PROJECT_VERSION_REF }}
        run: |
          echo "ENV: ${{ github.ref }}"
          env
          
      #- name: Update new version in krew-index
      #  uses: rajatjindal/krew-release-bot@v0.0.46
      #  if: ${{ github.event_name == 'workflow_dispatch' }}
      #  env:
      #    github.ref: ${{ env.PROJECT_VERSION_REF }}
      #  with:
      #    krew_template_file: 'plugins/.krew.yaml'
