on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Use version field:'
        type: boolean
      version:
        description: 'Version name be released: v0.0.0'
        type: string

name: Release to Krew

jobs:
  release:
    permissions:
        contents: read
    name: Release to Krew
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: vars
        run: |
          # - if a tag was selected
          if [[ '${{ github.ref }}'  =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            PROJECT_VERSION=${{ github.ref }}
            PROJECT_VERSION=$( echo $PROJECT_VERSION | sed 's|refs/tags/||g' )
          # - or the version number was given via text field
          elsif [ '${{inputs.confirm}}' == 'true' ] && [[ '${{inputs.version}}' =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
            PROJECT_VERSION='${{inputs.version}}'
          # - not a valid version
          else
            echo "ERROR: Invalid version given! Must have format 'v0.0.0'!" >&2
            false
          fi
          echo "PROJECT_VERSION=${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >>"$GITHUB_ENV"
