on:
  workflow_dispatch:

name: Release to Krew

jobs:
  release:
    permissions:
        contents: read
    name: Release to Krew
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: vars
        run: |
          if [[ '${{ github.ref }}'  =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]
          then
          PROJECT_VERSION=${{ github.ref }}
          PROJECT_VERSION=$( echo $PROJECT_VERSION | sed 's|refs/tags/||g' )
          echo "PROJECT_VERSION=${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >>"$GITHUB_ENV"
          else
            echo "ERROR: Invalid reverence given! Must be a tag in format 'v0.0.0'!" >&2
            false
          fi
